#!/bin/sh
#
# Starts busbox httpd
#

PID_FILE=/run/httpd.pid


start() {
    echo "Starting httpd..."
    start-stop-daemon -S -b -m -p $PID_FILE --exec httpd -- -p 80 -f -h "/root/www"
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    echo "Stopping httpd..."
    
    if [ -f $PID_FILE ]; then
		start-stop-daemon -K -q -p $PID_FILE
		[ $? = 0 ] && echo "OK" || echo "FAIL"

		rm -f $PID_FILE
	else
		echo "Not running"
	fi	

    rm -f $PID_FILE
}


case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart|reload)
        stop
        sleep 1
        start
    ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
