#!/bin/sh
#
# Starts busbox httpd
#

PID_FILE=/run/httpd.pid


start() {
    printf "Starting httpd..."
    start-stop-daemon -S -b -m -p $PID_FILE --exec httpd -- -p 80 -f -h "/root/www"
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    printf "Stopping httpd..."
    start-stop-daemon -K -p $PID_FILE
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}


case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart|reload)
        stop
        sleep 1
        start
    ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
