#!/bin/bash

## Mod's service management
##
## Copyright (C) 2025, Alexander K <https://github.com/drA1ex>
##
## This file may be distributed under the terms of the GNU GPLv3 license

SKIP_REBOOT_F="/tmp/zmod_skip_reboot"

restart() {
    echo "Received restart signal."

    
    # Mount rootfs
    mkdir -p /_root
    mount /dev/mmcblk0p6 /_root

    # Make sure boot scripts at it's place
    rm -f /_root/etc/init.d/S00fix
    ln -s /opt/config/mod/.shell/S00init /_root/etc/init.d/S00init

    if [ -f "$SKIP_REBOOT_F" ]; then
        echo "Skip."
        rm -f $SKIP_REBOOT_F
        
        exit 0
    fi
    
    reboot
}

case "$1" in
    restart)
        restart
    ;;
    *)
        echo "Usage: $0 (restart)}"
        exit 1
esac

exit 0
