#!/bin/bash

## Mod's service management
##
## Copyright (C) 2025 Alexander K <https://github.com/drA1ex>
##
## This file may be distributed under the terms of the GNU GPLv3 license

SKIP_REBOOT_F="/tmp/zmod_skip_reboot"

restart() {
    echo "Received restart signal."
    
    if [ -f "$SKIP_REBOOT_F" ]; then
        echo "Skip."
        rm -f $SKIP_REBOOT_F
        
        exit 0
    fi
    
    reboot
}

case "$1" in
    restart)
        restart
    ;;
    *)
        echo "Usage: $0 (restart)}"
        exit 1
esac

exit $?