#!/bin/sh

if [ -f /tmp/SKIP_ZMOD ]; then
    echo "Dropbear disabled due to SKIP_ZMOD mode"
    exit 0
fi

start() {
    printf "Starting dropbear: "
	killall dropbear
	/bin/dropbear -p 22
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    printf "Stopping dropbear: "
    killall dropbear
    echo "OK"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?