#!/bin/bash

## Service for zmod camera
##
## Copyright (C) 2025, Alexander K <https://github.com/drA1ex>
## Copyright (C) 2025, Sergei Rozhkov <https://github.com/ghzserg>
##
## This file may be distributed under the terms of the GNU GPLv3 license


if [ -f /tmp/SKIP_ZMOD ] || [ -f /tmp/SKIP_ZMOD_SOFT ]; then
    echo "Custom camera disabled due to SKIP_ZMOD mode"
    exit 0
fi

source /opt/config/mod/.shell/common.sh
CFG_PATH="/opt/config/mod_data/camera.conf"

# Create default configuration if needed
if [ ! -f "$CFG_PATH" ]; then
    cp "/opt/config/mod/.cfg/default/camera.conf" "$CFG_PATH"
fi


VIDEO="video0"

E_SHARPNESS=255
E_BRIGHTNESS=0
E_CONTRAST=255
E_GAMMA=10
E_GAIN=1

PID_FILE=/run/camera.pid
source "/opt/config/mod_data/camera.conf"

_VIDEO_P="/dev/${VIDEO}"


start() {
    enabled=$($CFG_SCRIPT $VAR_PATH --get "camera" "0")
    if [ "$enabled" -eq 1 ]; then
        /usr/bin/v4l2-ctl --set-fmt-video=width="${WIDTH}",height="${HEIGHT}",pixelformat=1
        start-stop-daemon -Sbm -p $PID_FILE --exec /opt/bin/mjpg_streamer -- -o "/opt/lib/mjpg-streamer/output_http.so -w /opt/mjpg-streamer/www -p 8080" -i  "/opt/lib/mjpg-streamer/input_uvc.so -d ${_VIDEO_P} -r ${WIDTH}x${HEIGHT} -f $FPS -b 1 -fs $(( WIDTH * HEIGHT * 2 ))"
        
        reload
    else
        echo "Camera disabled"
    fi
}

stop() {
    start-stop-daemon -K -p $PID_FILE 2>/dev/null >/dev/null
}

restart() {
    stop
    sleep 2
    start
}

reload() {
    if [ -f $PID_FILE ] && kill -0 "$(cat $PID_FILE)" 2>/dev/null; then
        v4l2-ctl --set-ctrl sharpness=${E_SHARPNESS} --device=${_VIDEO_P}
        v4l2-ctl --set-ctrl brightness=${E_BRIGHTNESS} --device=${_VIDEO_P}
        v4l2-ctl --set-ctrl contrast=${E_CONTRAST} --device=${_VIDEO_P}
        v4l2-ctl --set-ctrl gamma=${E_GAMMA} --device=${_VIDEO_P}
        v4l2-ctl --set-ctrl gain=${E_GAIN} --device=${_VIDEO_P}
    fi
}


case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
        restart
    ;;
    reload)
        reload
        echo "OK"
    ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload}"
        exit 1
esac

exit $?
