#!/bin/sh
#
# Start Camera
#


if ! [ -f /opt/config/mod_data/camera.conf ]
    then
        /root/printer_data/scripts/zcamera.sh off 1280 720 20 video0 NOTRESTART
fi

VIDEO="video0"
source /opt/config/mod_data/camera.conf
PID_FILE=/run/camera.pid

start() {
    if [ $START = "on" ]
        then
            /usr/bin/v4l2-ctl --set-fmt-video=width=${WIDTH},height=${HEIGHT},pixelformat=1
            start-stop-daemon -S -b -m -p $PID_FILE --exec /opt/mjpg-streamer/bin/mjpg_streamer -- -o "/opt/mjpg-streamer/lib/output_http.so -w /opt/mjpg-streamer/www -p 8080" -i  "/opt/mjpg-streamer/lib/input_uvc.so -d /dev/${VIDEO} -r ${WIDTH}x${HEIGHT} -f $FPS"
        else
            echo "Камера отключена"
    fi
}

stop() {
    start-stop-daemon -K -p $PID_FILE 2>/dev/null >/dev/null
}
restart() {
    stop
    sleep 2
    start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
