#!/bin/sh

## General service to control zmod services
##
## Copyright (C) 2025 Alexander K <https://github.com/drA1ex>
## Copyright (C) 2025 Sergei Rozhkov <https://github.com/ghzserg>
##
## This file may be distributed under the terms of the GNU GPLv3 license

MOD=/data/.mod/.zmod

START_PROC_DONE_F="${MOD}/tmp/start_proc_done"

unset LD_PRELOAD

start() {
  /etc/init.d/prepare.sh &
}

stop() {
    printf "Stopping moon: "
    chroot $MOD /opt/config/mod/.shell/root/stop.sh
    echo "OK"
}

up() {
    printf "Starting moon: "

    rm -f $START_PROC_DONE_F
    chroot $MOD /opt/config/mod/.shell/root/start.sh &

    for _ in $(seq 0 15); do
        test -f $START_PROC_DONE_F && break
        sleep 1
    done
    echo "OK"
}

case "$1" in
    up)
        up
        ;;
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|up}"
        exit 1
esac

exit $?
