#!/bin/sh

## General service to control zmod services
##
## Copyright (C) 2025, Alexander K <https://github.com/drA1ex>
## Copyright (C) 2025, Sergei Rozhkov <https://github.com/ghzserg>
##
## This file may be distributed under the terms of the GNU GPLv3 license

MOD=/data/.mod/.zmod

NOT_FIRST_LAUNCH_F="/tmp/not_first_launch"

unset LD_PRELOAD

start() {
    if [ -f "$NOT_FIRST_LAUNCH_F" ]; then echo "start() method meant to be only for fresh start!"; exit 1; fi
    /etc/init.d/prepare.sh &
}

stop() {
    echo "Stop Buildroot env..."
    chroot $MOD /opt/config/mod/.root/stop.sh
    echo "OK"
}

up() {
    echo "Starting Buildroot env..."
    chroot $MOD /opt/config/mod/.root/start.sh
    echo "OK"
}

case "$1" in
    start)
        start
    ;;
    up)
        up
    ;;
    stop)
        stop
    ;;
    restart|reload)
        stop

        while kill -0 $(cat "$MOD/run/moonraker.pid") > /dev/null  2>&1; do sleep 1; done
        while kill -0 $(cat "$MOD/run/httpd.pid") > /dev/null  2>&1; do sleep 1; done
        while kill -0 $(cat "$MOD/run/ntpd.pid") > /dev/null  2>&1; do sleep 1; done

        up
    ;;
    *)
        echo "Usage: $0 {start|stop|restart|up}"
        exit 1
esac

exit $?
